#!/usr/bin/env bash

##############################################################
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#####################################################################


## Environment configuration
# Hadoop installation
export HADOOP_VERSION=hadoop-1.2.1
export HADOOP_HOME=/pico/hadoop/software/hadoop/hadoop-1.2.1
export HADOOP_CONF_DIR=$CINECA_SCRATCH/hadoop-$PBS_JOBID/conf
export USE_REAL_DATASET=TRUE

export APP_JAR=${HADOOP_HOME}/hadoop-test-1.2.1.jar
export EXAMPLE_JAR=${HADOOP_HOME}/hadoop-examples-1.2.1.jar
export STREAMING_JAR=${HADOOP_HOME}/contrib/streaming/hadoop-streaming-1.2.1.jar



